version: '3.9'

services:

  # Database
  db:
    container_name: wp_mysql
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    ports: 
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite

   # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite     

  # Wordpress
  wordpress:
    container_name: wp_wordpress
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '80:80'
    restart: always
    volumes: ['wp_data:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: define('WP_ALLOW_MULTISITE', true );
    hostname: vidaswordpress.com.local
    labels:
      com.theimpossiblecode.expose.domain: "vidaswordpress.com.local" 
      com.theimpossiblecode.expose.domainIsHost: "true"
      com.theimpossiblecode.expose.subdomainHosts: "de at it"
    networks:
      wpsite:
          aliases:
            - vidaswordpress.com.local

# Pure FTP
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: wp_pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "db_data:/var/lib/mysql"
      - "wp_data:/var/www/html"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: admin
      FTP_USER_PASS: admin
      FTP_USER_HOME: /var
      FTP_USER_UID: 33
      FTP_USER_GID: 33
    restart: always

networks:
  wpsite:
volumes:
  db_data:
  wp_data: